services:
  redis:
    image: redis:7-alpine
    container_name: mailnotify-redis
    restart: always
    volumes:
      - redis_data:/data

  mailnotify-service:
    container_name: mailnotify-service
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - redis
    stdin_open: true
    tty: true

volumes:
  redis_data: