spring.application.name=mailnotify-service
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.threads.virtual.enabled=true
app.imap.host=${IMAP_HOST}
app.imap.user=${IMAP_USER}
app.imap.key=${IMAP_KEY}
app.tg.token=${BOT_TOKEN}
app.tg.chat-id=${CHAT_ID}