spring.application.name=mailnotify-service
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.threads.virtual.enabled=true
app.imap.host=${IMAP_HOST:gmail.com}
app.imap.user=${IMAP_USER:test_user}
app.imap.key=${IMAP_KEY:test}
app.tg.token=${BOT_TOKEN:token}
app.tg.chat-id=${CHAT_ID:123}
debug=true