spring.application.name=mailnotify-service

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# Just for fun
spring.threads.virtual.enabled=true

# Mail
app.imap.host=${IMAP_HOST}
app.imap.user=${IMAP_USER}
app.imap.key=${IMAP_KEY}

# Telegram
app.tg.token=${BOT_TOKEN}
app.tg.chat-id=${CHAT_ID}